# Generated by Django 5.0 on 2023-12-13 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pdf', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
