# Generated by Django 5.0 on 2024-01-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='institution',
        ),
    ]
