# Generated by Django 5.0 on 2023-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='articles.author'),
        ),
    ]
