# Generated by Django 5.0 on 2024-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_author_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='institution',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
