# Generated by Django 5.0 on 2023-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0005_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='articles.article'),
        ),
    ]
